# THIS FILE IS GENERATED, DO NOT EDIT DIRECTLY
# 
# To change this file, see `bin/connector_config/Generate.hs` at
# https://github.com/CT075/fe8-archipelago

locations = [
  ("Complete Prologue", 0),
  ("Complete Chapter 1", 1),
  ("Complete Chapter 2", 2),
  ("Complete Chapter 3", 3),
  ("Complete Chapter 4", 4),
  ("Complete Chapter 5", 5),
  ("Complete Chapter 5x", 6),
  ("Complete Chapter 6", 7),
  ("Complete Chapter 7", 8),
  ("Complete Chapter 8", 9),
  ("Complete Chapter 9", 10),
  ("Complete Chapter 10", 11),
  ("Complete Chapter 11", 12),
  ("Complete Chapter 12", 13),
  ("Complete Chapter 13", 14),
  ("Complete Chapter 14", 15),
  ("Complete Chapter 15", 16),
  ("Complete Chapter 16", 17),
  ("Complete Chapter 17", 18),
  ("Complete Chapter 18", 19),
  ("Complete Chapter 19", 20),
  ("Complete Chapter 20", 21),
  ("Defeat Lyon", 22),
  ("Defeat Formortiis", 23),
  ("Complete Tower of Valni 1", 24),
  ("Complete Tower of Valni 2", 25),
  ("Complete Tower of Valni 3", 26),
  ("Complete Tower of Valni 4", 27),
  ("Complete Tower of Valni 5", 28),
  ("Complete Tower of Valni 6", 29),
  ("Complete Tower of Valni 7", 30),
  ("Complete Tower of Valni 8", 31),
  ("Complete Lagdou Ruins 1", 32),
  ("Complete Lagdou Ruins 2", 33),
  ("Complete Lagdou Ruins 3", 34),
  ("Complete Lagdou Ruins 4", 35),
  ("Complete Lagdou Ruins 5", 36),
  ("Complete Lagdou Ruins 6", 37),
  ("Complete Lagdou Ruins 7", 38),
  ("Complete Lagdou Ruins 8", 39),
  ("Complete Lagdou Ruins 9", 40),
  ("Complete Lagdou Ruins 10", 41),
  ("Za'ha Woods Skirmish", 42),
  ("Adlas Plains Skirmish", 43),
  ("Teras Plateau Skirmish", 44),
  ("Hamill Canyon Skirmish", 45),
  ("Bethroen Skirmish", 46),
  ("Za'albul Marsh Skirmish", 47),
  ("Narube River Skirmish", 48),
  ("Neleras Peak Skirmish", 49),
  ("Melkaen Coast Skirmish", 50),
  ("Sieglinde Received", 51),
  ("Siegmund Received", 52),
  ("Gleipnir Received", 53),
  ("Garm Received", 54),
  ("Nidhogg Received", 55),
  ("Vidofnir Received", 56),
  ("Excalibur Received", 57),
  ("Audhulma Received", 58),
  ("Ivaldi Received", 59),
  ("Latona Received", 60),
  ("Seth Recruited", 61),
  ("Franz Recruited", 62),
  ("Gilliam Recruited", 63),
  ("Vanessa Recruited", 64),
  ("Moulder Recruited", 65),
  ("Ross Recruited", 66),
  ("Garcia Recruited", 67),
  ("Neimi Recruited", 68),
  ("Colm Recruited", 69),
  ("Artur Recruited", 70),
  ("Lute Recruited", 71),
  ("Natasha Recruited", 72),
  ("Joshua Recruited", 73),
  ("Forde Recruited", 74),
  ("Kyle Recruited", 75),
  ("Tana Recruited", 76),
  ("Amelia Recruited", 77),
  ("Innes Recruited", 78),
  ("Gerik Recruited", 79),
  ("Tethys Recruited", 80),
  ("Marisa Recruited", 81),
  ("L'Arachel Recruited", 82),
  ("Dozla Recruited", 83),
  ("Saleh Recruited", 84),
  ("Ewan Recruited", 85),
  ("Cormag Recruited", 86),
  ("Rennac Recruited", 87),
  ("Duessel Recruited", 88),
  ("Knoll Recruited", 89),
  ("Myrrh Recruited", 90),
  ("Syrene Recruited", 91),
]

items = [
  ("Progressive Level Cap", 0),
  ("Progressive Weapon Level (Sword)", 1),
  ("Progressive Weapon Level (Lance)", 2),
  ("Progressive Weapon Level (Axe)", 3),
  ("Progressive Weapon Level (Bow)", 4),
  ("Progressive Weapon Level (Staff)", 5),
  ("Progressive Weapon Level (Anima)", 6),
  ("Progressive Weapon Level (Light)", 7),
  ("Progressive Weapon Level (Dark)", 8),
  ("Sieglinde", 9),
  ("Siegmund", 10),
  ("Gleipnir", 11),
  ("Garm", 12),
  ("Nidhogg", 13),
  ("Vidofnir", 14),
  ("Excalibur", 15),
  ("Audhulma", 16),
  ("Ivaldi", 17),
  ("Latona", 18),
  ("AngelicRobe", 19),
  ("EnergyRing", 20),
  ("SecretBook", 21),
  ("Speedwings", 22),
  ("GoddessIcon", 23),
  ("DragonShield", 24),
  ("Talisman", 25),
  ("BodyRing", 26),
  ("Boots", 27),
  ("KnightCrest", 28),
  ("HeroCrest", 29),
  ("OrionsBolt", 30),
  ("GuidingRing", 31),
  ("ElysianWhip", 32),
  ("OceanSeal", 33),
  ("MasterSeal", 34),
  ("Deploy Seth", 35),
  ("Deploy Franz", 36),
  ("Deploy Gilliam", 37),
  ("Deploy Vanessa", 38),
  ("Deploy Moulder", 39),
  ("Deploy Ross", 40),
  ("Deploy Garcia", 41),
  ("Deploy Neimi", 42),
  ("Deploy Colm", 43),
  ("Deploy Artur", 44),
  ("Deploy Lute", 45),
  ("Deploy Natasha", 46),
  ("Deploy Joshua", 47),
  ("Deploy Forde", 48),
  ("Deploy Kyle", 49),
  ("Deploy Tana", 50),
  ("Deploy Amelia", 51),
  ("Deploy Innes", 52),
  ("Deploy Gerik", 53),
  ("Deploy Tethys", 54),
  ("Deploy Marisa", 55),
  ("Deploy L'Arachel", 56),
  ("Deploy Dozla", 57),
  ("Deploy Saleh", 58),
  ("Deploy Ewan", 59),
  ("Deploy Cormag", 60),
  ("Deploy Rennac", 61),
  ("Deploy Duessel", 62),
  ("Deploy Knoll", 63),
  ("Deploy Myrrh", 64),
  ("Deploy Syrene", 65),
  ("Progressive Seth Deployment", 66),
  ("Paladin Promotion", 67),
  ("General Promotion", 68),
  ("Hero Promotion", 69),
  ("Swordmaster Promotion", 70),
  ("Assassin Promotion", 71),
  ("Sniper Promotion", 72),
  ("Ranger Promotion", 73),
  ("Wyvern Lord Promotion", 74),
  ("Wyvern Knight Promotion", 75),
  ("Sage Promotion", 76),
  ("Mage Knight Promotion", 77),
  ("Bishop Promotion", 78),
  ("Druid Promotion", 79),
  ("Summoner Promotion", 80),
  ("Rogue Promotion", 81),
  ("Great Knight Promotion", 82),
  ("Warrior Promotion", 83),
  ("Berserker Promotion", 84),
  ("Falcon Knight Promotion", 85),
  ("Valkyrie Promotion", 86),
  ("Journeyman Promotion", 87),
  ("Pupil Promotion", 88),
  ("Recruit Promotion", 89),
]
FREE_UNIT_LOC = {
  "Seth": {|ROM_BASE:archipelagoOptions|}+{|fake_freeSethOffs|},
  "Franz": {|ROM_BASE:archipelagoOptions|}+{|fake_freeFranzOffs|},
  "Gilliam": {|ROM_BASE:archipelagoOptions|}+{|fake_freeGilliamOffs|},
  "Vanessa": {|ROM_BASE:archipelagoOptions|}+{|fake_freeVanessaOffs|},
  "Moulder": {|ROM_BASE:archipelagoOptions|}+{|fake_freeMoulderOffs|},
  "Ross": {|ROM_BASE:archipelagoOptions|}+{|fake_freeRossOffs|},
  "Garcia": {|ROM_BASE:archipelagoOptions|}+{|fake_freeGarciaOffs|},
  "Neimi": {|ROM_BASE:archipelagoOptions|}+{|fake_freeNeimiOffs|},
  "Colm": {|ROM_BASE:archipelagoOptions|}+{|fake_freeColmOffs|},
  "Artur": {|ROM_BASE:archipelagoOptions|}+{|fake_freeArturOffs|},
  "Lute": {|ROM_BASE:archipelagoOptions|}+{|fake_freeLuteOffs|},
  "Natasha": {|ROM_BASE:archipelagoOptions|}+{|fake_freeNatashaOffs|},
  "Joshua": {|ROM_BASE:archipelagoOptions|}+{|fake_freeJoshuaOffs|},
  "Forde": {|ROM_BASE:archipelagoOptions|}+{|fake_freeFordeOffs|},
  "Kyle": {|ROM_BASE:archipelagoOptions|}+{|fake_freeKyleOffs|},
  "Tana": {|ROM_BASE:archipelagoOptions|}+{|fake_freeTanaOffs|},
  "Amelia": {|ROM_BASE:archipelagoOptions|}+{|fake_freeAmeliaOffs|},
  "Innes": {|ROM_BASE:archipelagoOptions|}+{|fake_freeInnesOffs|},
  "Gerik": {|ROM_BASE:archipelagoOptions|}+{|fake_freeGerikOffs|},
  "Tethys": {|ROM_BASE:archipelagoOptions|}+{|fake_freeTethysOffs|},
  "Marisa": {|ROM_BASE:archipelagoOptions|}+{|fake_freeMarisaOffs|},
  "L'Arachel": {|ROM_BASE:archipelagoOptions|}+{|fake_freeL'ArachelOffs|},
  "Dozla": {|ROM_BASE:archipelagoOptions|}+{|fake_freeDozlaOffs|},
  "Saleh": {|ROM_BASE:archipelagoOptions|}+{|fake_freeSalehOffs|},
  "Ewan": {|ROM_BASE:archipelagoOptions|}+{|fake_freeEwanOffs|},
  "Cormag": {|ROM_BASE:archipelagoOptions|}+{|fake_freeCormagOffs|},
  "Rennac": {|ROM_BASE:archipelagoOptions|}+{|fake_freeRennacOffs|},
  "Duessel": {|ROM_BASE:archipelagoOptions|}+{|fake_freeDuesselOffs|},
  "Knoll": {|ROM_BASE:archipelagoOptions|}+{|fake_freeKnollOffs|},
  "Myrrh": {|ROM_BASE:archipelagoOptions|}+{|fake_freeMyrrhOffs|},
  "Syrene": {|ROM_BASE:archipelagoOptions|}+{|fake_freeSyreneOffs|},
}
SLOT_NAME_ADDR = {|archipelagoInfo|}
SUPER_DEMON_KING_OFFS = {|ROM_BASE:archipelagoOptions|}+{|fake_superDemonKingOffs|}
LOCKPICK_USABILITY_OFFS = {|ROM_BASE:archipelagoOptions|}+{|fake_lockpickUsabilityOffs|}
DEATH_LINK_KIND_OFFS = {|ROM_BASE:archipelagoOptions|}+{|fake_deathLinkKindOffs|}
LEVEL_CAPS_OFFS = {|ROM_BASE:archipelagoOptions|}+{|fake_enableLevelCapsOffs|}
WEAPON_LEVEL_CAPS_OFFS = {|ROM_BASE:archipelagoOptions|}+{|fake_enableWeaponLevelCapsOffs|}
PROMOTION_UNLOCKS_OFFS = {|ROM_BASE:archipelagoOptions|}+{|fake_promotionUnlocksOffs|}
RECRUIT_CHECKS_OFFS = {|ROM_BASE:archipelagoOptions|}+{|fake_recruitChecksEnabledOffs|}
LOCATION_INFO_OFFS = {|ROM_BASE:locItems|}
LOCATION_INFO_SIZE = 4
ARCHIPELAGO_RECEIVED_ITEM_ADDR = {|receivedAPItem|}
ARCHIPELAGO_NUM_RECEIVED_ITEMS_ADDR = {|receivedItemIndex|}
ARCHIPELAGO_DEATHLINK_IN = {|deathLinkIn|}
ARCHIPELAGO_DEATHLINK_OUT = {|deathLinkOut|}
ARCHIPELAGO_DEATHLINK_READY = {|deathLinkReady|}
FLAGS_ADDR = {|checkedLocations|}
FLAGS_SIZE = 12
