# THIS FILE IS GENERATED, DO NOT EDIT DIRECTLY
# 
# To change this file, see `bin/connector_config/Generate.hs` at
# https://github.com/CT075/fe8-archipelago

locations = [
  ("Complete Prologue", 0),
  ("Complete Chapter 1", 1),
  ("Complete Chapter 2", 2),
  ("Complete Chapter 3", 3),
  ("Complete Chapter 4", 4),
  ("Complete Chapter 5", 5),
  ("Complete Chapter 5x", 6),
  ("Complete Chapter 6", 7),
  ("Complete Chapter 7", 8),
  ("Complete Chapter 8", 9),
  ("Complete Chapter 9", 10),
  ("Complete Chapter 10", 11),
  ("Complete Chapter 11", 12),
  ("Complete Chapter 12", 13),
  ("Complete Chapter 13", 14),
  ("Complete Chapter 14", 15),
  ("Complete Chapter 15", 16),
  ("Complete Chapter 16", 17),
  ("Complete Chapter 17", 18),
  ("Complete Chapter 18", 19),
  ("Complete Chapter 19", 20),
  ("Complete Chapter 20", 21),
  ("Defeat Lyon", 22),
  ("Defeat Formortiis", 23),
  ("Complete Tower of Valni 1", 24),
  ("Complete Tower of Valni 2", 25),
  ("Complete Tower of Valni 3", 26),
  ("Complete Tower of Valni 4", 27),
  ("Complete Tower of Valni 5", 28),
  ("Complete Tower of Valni 6", 29),
  ("Complete Tower of Valni 7", 30),
  ("Complete Tower of Valni 8", 31),
  ("Complete Lagdou Ruins 1", 32),
  ("Complete Lagdou Ruins 2", 33),
  ("Complete Lagdou Ruins 3", 34),
  ("Complete Lagdou Ruins 4", 35),
  ("Complete Lagdou Ruins 5", 36),
  ("Complete Lagdou Ruins 6", 37),
  ("Complete Lagdou Ruins 7", 38),
  ("Complete Lagdou Ruins 8", 39),
  ("Complete Lagdou Ruins 9", 40),
  ("Complete Lagdou Ruins 10", 41),
  ("Sieglinde Received", 42),
  ("Siegmund Received", 43),
  ("Gleipnir Received", 44),
  ("Garm Received", 45),
  ("Nidhogg Received", 46),
  ("Vidofnir Received", 47),
  ("Excalibur Received", 48),
  ("Audhulma Received", 49),
  ("Ivaldi Received", 50),
  ("Latona Received", 51),
  ("Seth Recruited", 52),
  ("Franz Recruited", 53),
  ("Gilliam Recruited", 54),
  ("Vanessa Recruited", 55),
  ("Moulder Recruited", 56),
  ("Ross Recruited", 57),
  ("Garcia Recruited", 58),
  ("Neimi Recruited", 59),
  ("Colm Recruited", 60),
  ("Artur Recruited", 61),
  ("Lute Recruited", 62),
  ("Natasha Recruited", 63),
  ("Joshua Recruited", 64),
  ("Forde Recruited", 65),
  ("Kyle Recruited", 66),
  ("Tana Recruited", 67),
  ("Amelia Recruited", 68),
  ("Innes Recruited", 69),
  ("Gerik Recruited", 70),
  ("Tethys Recruited", 71),
  ("Marisa Recruited", 72),
  ("L'Arachel Recruited", 73),
  ("Dozla Recruited", 74),
  ("Saleh Recruited", 75),
  ("Ewan Recruited", 76),
  ("Cormag Recruited", 77),
  ("Rennac Recruited", 78),
  ("Duessel Recruited", 79),
  ("Knoll Recruited", 80),
  ("Myrrh Recruited", 81),
  ("Syrene Recruited", 82),
]

items = [
  ("Progressive Level Cap", 0),
  ("Progressive Weapon Level (Sword)", 1),
  ("Progressive Weapon Level (Lance)", 2),
  ("Progressive Weapon Level (Axe)", 3),
  ("Progressive Weapon Level (Bow)", 4),
  ("Progressive Weapon Level (Staff)", 5),
  ("Progressive Weapon Level (Anima)", 6),
  ("Progressive Weapon Level (Light)", 7),
  ("Progressive Weapon Level (Dark)", 8),
  ("Sieglinde", 9),
  ("Siegmund", 10),
  ("Gleipnir", 11),
  ("Garm", 12),
  ("Nidhogg", 13),
  ("Vidofnir", 14),
  ("Excalibur", 15),
  ("Audhulma", 16),
  ("Ivaldi", 17),
  ("Latona", 18),
  ("AngelicRobe", 19),
  ("EnergyRing", 20),
  ("SecretBook", 21),
  ("Speedwings", 22),
  ("GoddessIcon", 23),
  ("DragonShield", 24),
  ("Talisman", 25),
  ("BodyRing", 26),
  ("Boots", 27),
  ("KnightCrest", 28),
  ("HeroCrest", 29),
  ("OrionsBolt", 30),
  ("GuidingRing", 31),
  ("ElysianWhip", 32),
  ("OceanSeal", 33),
  ("MasterSeal", 34),
  ("Deploy Seth", 35),
  ("Deploy Franz", 36),
  ("Deploy Gilliam", 37),
  ("Deploy Vanessa", 38),
  ("Deploy Moulder", 39),
  ("Deploy Ross", 40),
  ("Deploy Garcia", 41),
  ("Deploy Neimi", 42),
  ("Deploy Colm", 43),
  ("Deploy Artur", 44),
  ("Deploy Lute", 45),
  ("Deploy Natasha", 46),
  ("Deploy Joshua", 47),
  ("Deploy Forde", 48),
  ("Deploy Kyle", 49),
  ("Deploy Tana", 50),
  ("Deploy Amelia", 51),
  ("Deploy Innes", 52),
  ("Deploy Gerik", 53),
  ("Deploy Tethys", 54),
  ("Deploy Marisa", 55),
  ("Deploy L'Arachel", 56),
  ("Deploy Dozla", 57),
  ("Deploy Saleh", 58),
  ("Deploy Ewan", 59),
  ("Deploy Cormag", 60),
  ("Deploy Rennac", 61),
  ("Deploy Duessel", 62),
  ("Deploy Knoll", 63),
  ("Deploy Myrrh", 64),
  ("Deploy Syrene", 65),
  ("Progressive Seth Deployment", 66),
]
SLOT_NAME_ADDR = {|archipelagoInfo|}
SUPER_DEMON_KING_OFFS = {|ROM_BASE:archipelagoOptions|}
LOCKPICK_USABILITY_OFFS = {|ROM_BASE:archipelagoOptions|}+1
DEATH_LINK_KIND_OFFS = {|ROM_BASE:archipelagoOptions|}+2
LOCATION_INFO_OFFS = {|ROM_BASE:locItems|}
LOCATION_INFO_SIZE = 4
ARCHIPELAGO_RECEIVED_ITEM_ADDR = {|receivedAPItem|}
ARCHIPELAGO_NUM_RECEIVED_ITEMS_ADDR = {|receivedItemIndex|}
ARCHIPELAGO_DEATHLINK_IN = {|deathLinkIn|}
ARCHIPELAGO_DEATHLINK_OUT = {|deathLinkOut|}
ARCHIPELAGO_DEATHLINK_READY = {|deathLinkReady|}
FLAGS_ADDR = {|checkedLocations|}
FLAGS_SIZE = 12
